### ISSUE TITLE
Type error: preg_match() expects parameter 2 to be string, null given

### ISSUE THREAD

**Issue by pdiveris** [deanblackborough/php-quill-renderer#43]
Hi there,

With some (pasted) text I get the error you see in the subject line. It happens when your ops contains a line like this

```
		{"insert": },
```
which I have no idea how and why it happens. This causes "runtime" errors (and a consequent 500 as I am using your lovely code as an asynchronous renderer.) I have had to add the following in three places (but there might be still more that need the extra check): `! (null ===  $delta['insert']) &&`.

The lines I updates were 216, 246 and 345 but of course things might have moved a bit now!

I've attached a screenshot of my Chrome's console so you can see what i encountered. My extra check seems to have fixed it so I will attach my version of Html.php to this report in addition to requesting a pul, as I don't know what your pull request policies are. By all means, incorporate my fix if you prefer it that way, or accept the request!

Thank you,

Petros

![screen shot 2018-04-14 at 17 19 40](https://user-images.githubusercontent.com/1022373/38770390-65ce0092-400a-11e8-8562-d806aab299cf.png)

[Html.php.txt](https://github.com/deanblackborough/php-quill-renderer/files/1910621/Html.php.txt)

**Comment by deanblackborough** [comment]
@pdiveris  Thank you.

I've had a quick look at your changes and they break the build, there should only be one failing test, 24 fail because the code is trying to use an undefined index which makes sense given the changes.

A better solution would be dropping those deltas before they reach the rest of the code, I'm not sure how you have invalid deltas (missing "") but I'd suggest a new method, called before localLists() in parse() to drop invalid/empty deltas as early as possible by doing a similar check, something like.

```
// Untested code

$deltas = $this->deltas['ops'];
$this->deltas = array();

foreach ($deltas as $k => $delta) {
    if (array_key_exists('insert', $delta) === true &&
    $delta['insert'] !== null) {
         $this->deltas[] = delta;
    }
}

```

If I get time tomorrow I'll add it or you could update your PR, it will need a test as well, I don't want the bug to reappear at a later date or in version 3.0.

You'll get credited in the README, everyone does, I very much appreciate bug submissions.

**Comment by pdiveris** [comment]
Thank you  for coming back to me. I am working on it too, there is something odd in these deltas, which came from a copy paste of  one line into the editor. Will get back to it tomorrow and let you know.

⁣Sent from BlueMail ​

**Comment by pdiveris** [comment]
OK, I can confirm that when pasting from pages such as this:

https://www.diveris.org/habari/some-thoughts-on-may-the-election-and-the-eu

<img width="653" alt="screen shot 2018-04-15 at 10 32 12" src="https://user-images.githubusercontent.com/1022373/38777000-506d88ec-4098-11e8-81c9-afd78e439828.png">

I am getting a series of `"insert":null` ops. Here's what this particular paste produced in terms of ops

`{"ops":[{"insert":"Theresa May"},{"attributes":{"align":"justify","header":4},"insert":null},{"insert":"As you almost certainly know by now, Theresa May announced in early April 2017 a surprise general election. The accepted wisdom is that with this election\u00a0"},{"attributes":{"align":"justify"},"insert":null},{"attributes":{"header":4},"insert":null}]}`

So, a cleanup is indeed required.

**Comment by pdiveris** [comment]
OK, the plot thickens. Quill adds a newline 'insert' op after every op. In an ugly fashion, those ops ,might well contain the formatting for your string. Look at the attached screenshot. The H1 and justify attrs for the text sitting at position 0 are attached to an operation which inserts a new line. I have no idea what problem Chen was trying to solve when he implemented that, but it only causes problems. In my case, since I was pushing the text to be rendered on a server component via async calls it means that it broke JSON and I got nulls instead. So, I am looking now at merging those in a single operation. Let me know your thoughts on this.

https://github.com/quilljs/quill/issues/890

**Comment by deanblackborough** [comment]
I've just released an update that removes any inserts which are null.

I've not seen anything like the above before, up till now I've only seen deltas with either content in the insert or at a minimum newlines.

I'll look into this for version v3.00, I'm starting development this evening and have a better design so if there have been changes it will be easier to deal with them.

For now I will leave this issue open as it is handy to collect all the data, I've closed your pull request because my changes deal with the original issue. One of the first tasks for version 3.00 will be making sure Quill generates the same deltas as I'm testing in my tests.
